# Generated by Django 3.2.8 on 2021-10-19 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_url', models.CharField(max_length=1024)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('link', models.CharField(blank=True, max_length=1024)),
                ('subtitle', models.CharField(blank=True, max_length=2048)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('pub_dttm_offset', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author', models.CharField(blank=True, max_length=200)),
                ('pub_dttm', models.DateTimeField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planet.feed')),
            ],
        ),
    ]
